"""M4 TDD tests: Gemma arbitration wired into stage-A and stage-B pipelines.

All tests use injected fake judges — no real Ollama server is ever contacted.
The existing test_judge.py covers the real-HTTP-failure path.

FakeJudge implements the same protocol as GemmaJudge:
  - write_profile(name, stats) -> str
  - arbitrate(path, rule_book) -> Verdict
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytest.importorskip("PIL")

from photovault.core.judge.ollama_client import JudgeUnavailable, Verdict
from photovault.core.score.engine import KEEP, MAYBE, REJECT
from photovault.core.score.pipeline import ApplyReport, apply_to_folder
from photovault.settings import Settings
from photovault.tests.test_clip_embed import FakeEmbedder


# --------------------------------------------------------------------------- #
# FakeJudge: injectable test double for GemmaJudge
# --------------------------------------------------------------------------- #
class FakeJudge:
    """Deterministic test double implementing the GemmaJudge protocol.

    write_profile: returns a fixed markdown string containing the profile name.
    arbitrate: keeps images whose filename contains 'keep', rejects the rest.
    """

    def __init__(self, verdict_keep: bool = True, reason: str = "fake reason"):
        self.verdict_keep = verdict_keep
        self.reason = reason
        # Track calls for assertions.
        self.arbitrate_calls: list[str] = []
        self.write_profile_calls: list[tuple[str, dict]] = []

    def write_profile(self, name: str, stats: dict) -> str:
        self.write_profile_calls.append((name, stats))
        return f"# Taste Profile: {name}\n\nFake rule-book generated by FakeJudge.\n"

    def arbitrate(self, image_path: str | Path, rule_book: str) -> Verdict:
        self.arbitrate_calls.append(str(image_path))
        return Verdict(keep=self.verdict_keep, reason=self.reason)


class UnavailableJudge:
    """Always raises JudgeUnavailable — simulates an unreachable Ollama server."""

    def write_profile(self, name: str, stats: dict) -> str:
        raise JudgeUnavailable("simulated: Ollama not running")

    def arbitrate(self, image_path: str | Path, rule_book: str) -> Verdict:
        raise JudgeUnavailable("simulated: Ollama not running")


def _fake_blink(_arr):
    """No mediapipe in tests — pretend nothing blinked."""
    return None


# --------------------------------------------------------------------------- #
# Stage-B: arbitration wired into apply_to_folder
# --------------------------------------------------------------------------- #
class TestStageB:
    """The maybe band gets arbitrated by an injected judge."""

    def _run(
        self,
        new_photos: Path,
        settings: Settings,
        learned_profile: str,
        judge=None,
        **kwargs,
    ) -> ApplyReport:
        return apply_to_folder(
            new_photos,
            learned_profile,
            settings,
            embedder=FakeEmbedder(),
            blink_fn=_fake_blink,
            judge=judge,
            **kwargs,
        )

    def test_maybe_items_flipped_to_keep_by_fake_judge(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """When judge keeps everything, all maybe items become keep."""
        fake = FakeJudge(verdict_keep=True, reason="looks great")
        report = self._run(new_photos, settings, learned_profile, judge=fake)

        # If there were any maybe items, they should all be flipped now.
        assert report.n_maybe == 0 or report.n_arbitrated == 0
        # n_keep + n_maybe + n_reject == n_images still holds.
        assert report.n_keep + report.n_maybe + report.n_reject == report.n_images

    def test_maybe_items_flipped_to_reject_by_fake_judge(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """When judge rejects everything, all maybe items become reject."""
        fake = FakeJudge(verdict_keep=False, reason="looks bad")
        report = self._run(new_photos, settings, learned_profile, judge=fake)

        assert report.n_maybe == 0 or report.n_arbitrated == 0
        assert report.n_keep + report.n_maybe + report.n_reject == report.n_images

    def test_n_arbitrated_reflects_how_many_maybes_were_decided(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """n_arbitrated equals the number of ScoreResults the judge decided."""
        fake = FakeJudge(verdict_keep=True)
        # Force wide maybe band so most items end up in maybe.
        settings.score.keep_above = 1.0   # nothing scores >= 1.0 -> only maybe or reject
        settings.score.reject_below = 0.0  # nothing scores < 0.0 -> so gate-pass -> maybe
        report = self._run(new_photos, settings, learned_profile, judge=fake)

        # All non-gated items should have been arbitrated.
        assert report.n_arbitrated > 0
        assert report.n_maybe == 0  # all arbitrated away
        assert report.n_arbitrated == len(fake.arbitrate_calls)

    def test_gemma_reason_appended_to_reasons_list(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """The judge's reason is appended as 'gemma: <reason>' on each decided item."""
        fake = FakeJudge(verdict_keep=True, reason="beautiful light")
        settings.score.keep_above = 1.0
        settings.score.reject_below = 0.0
        report = self._run(new_photos, settings, learned_profile, judge=fake)

        decided = [r for r in report.results if "gemma:" in " ".join(r.reasons)]
        assert len(decided) == report.n_arbitrated
        for r in decided:
            assert any("gemma:" in reason for reason in r.reasons)
            assert any("beautiful light" in reason for reason in r.reasons)

    def test_no_llm_flag_leaves_maybe_untouched(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """With no_llm=True, maybe items stay as maybe and n_arbitrated is 0."""
        fake = FakeJudge(verdict_keep=True)
        settings.score.keep_above = 1.0
        settings.score.reject_below = 0.0
        report = self._run(
            new_photos, settings, learned_profile, judge=fake, no_llm=True
        )

        assert report.n_arbitrated == 0
        assert len(fake.arbitrate_calls) == 0
        # Some note about LLM being disabled/skipped.
        combined = " ".join(report.notes).lower()
        assert "llm" in combined or "arbitrat" in combined

    def test_judge_none_without_llm_leaves_maybe(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """When judge=None and settings.llm.enabled=False, maybe items stay maybe."""
        settings.llm.enabled = False
        settings.score.keep_above = 1.0
        settings.score.reject_below = 0.0
        report = self._run(new_photos, settings, learned_profile, judge=None)

        assert report.n_arbitrated == 0
        combined = " ".join(report.notes).lower()
        assert "llm" in combined or "arbitrat" in combined

    def test_judge_unavailable_leaves_maybe_with_note(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """JudgeUnavailable during arbitration: items stay maybe, note added."""
        settings.score.keep_above = 1.0
        settings.score.reject_below = 0.0
        report = self._run(
            new_photos, settings, learned_profile, judge=UnavailableJudge()
        )

        assert report.n_arbitrated == 0
        combined = " ".join(report.notes).lower()
        # A note indicating why arbitration didn't happen.
        assert "unavailable" in combined or "judge" in combined

    def test_keep_reject_never_arbitrated(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """Only maybe items get sent to the judge; keep and reject items are untouched."""
        fake = FakeJudge(verdict_keep=True)
        # Default bands: some items will be keep, some reject, some maybe.
        report = self._run(new_photos, settings, learned_profile, judge=fake)

        # The number of arbitrate calls must equal n_arbitrated, not total images.
        assert len(fake.arbitrate_calls) == report.n_arbitrated
        # Specifically: keep/reject items before arbitration should not appear in calls.
        # Since we flip all maybe to keep (verdict_keep=True), n_maybe == 0 after.
        assert report.n_arbitrated >= 0

    def test_apply_report_has_n_arbitrated_field(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """ApplyReport exposes n_arbitrated with a sensible default."""
        fake = FakeJudge(verdict_keep=True)
        report = self._run(new_photos, settings, learned_profile, judge=fake)
        assert hasattr(report, "n_arbitrated")
        assert isinstance(report.n_arbitrated, int)
        assert report.n_arbitrated >= 0

    def test_counts_consistent_after_arbitration(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """n_keep + n_maybe + n_reject == n_images regardless of arbitration outcome."""
        for keep in [True, False]:
            fake = FakeJudge(verdict_keep=keep)
            report = self._run(new_photos, settings, learned_profile, judge=fake)
            assert report.n_keep + report.n_maybe + report.n_reject == report.n_images


# --------------------------------------------------------------------------- #
# Stage-A: injectable judge in learn_from_folder
# --------------------------------------------------------------------------- #
class TestStageA:
    """learn_from_folder wires the injected judge into profile.md generation."""

    def test_fake_judge_text_lands_in_profile_md(
        self, catalog_folder: Path, settings: Settings
    ):
        """When a FakeJudge is injected, its output is written to profile.md."""
        from photovault.core.learn import learn_from_folder
        from photovault.core.profile import load_profile

        fake = FakeJudge()
        settings.llm.enabled = True  # must be enabled for judge to be called

        report = learn_from_folder(
            catalog_folder, "proftest", settings, use_llm=True, judge=fake
        )

        assert report.llm_used is True
        prof = load_profile(settings.profiles_dir, "proftest")
        assert prof.profile_md is not None
        # FakeJudge.write_profile returns text containing the profile name.
        assert "proftest" in prof.profile_md
        assert "FakeJudge" in prof.profile_md

    def test_injected_judge_write_profile_called_with_name_and_stats(
        self, catalog_folder: Path, settings: Settings
    ):
        """The injected judge's write_profile is called with the profile name + stats."""
        from photovault.core.learn import learn_from_folder

        fake = FakeJudge()
        settings.llm.enabled = True

        learn_from_folder(
            catalog_folder, "check_args", settings, use_llm=True, judge=fake
        )

        assert len(fake.write_profile_calls) == 1
        called_name, called_stats = fake.write_profile_calls[0]
        assert called_name == "check_args"
        assert isinstance(called_stats, dict)
        assert "keep_rate" in called_stats or len(called_stats) > 0

    def test_unavailable_judge_writes_placeholder_and_sets_llm_used_false(
        self, catalog_folder: Path, settings: Settings
    ):
        """When an injected judge raises JudgeUnavailable, placeholder is written."""
        from photovault.core.learn import learn_from_folder
        from photovault.core.profile import load_profile

        settings.llm.enabled = True

        report = learn_from_folder(
            catalog_folder,
            "unavail_test",
            settings,
            use_llm=True,
            judge=UnavailableJudge(),
        )

        assert report.llm_used is False
        assert "unavailable" in report.llm_note.lower()

        prof = load_profile(settings.profiles_dir, "unavail_test")
        # The placeholder contains boilerplate text (not FakeJudge's output).
        assert prof.profile_md is not None
        assert "placeholder" in prof.profile_md.lower() or "Taste Profile" in prof.profile_md

    def test_judge_not_called_when_use_llm_false(
        self, catalog_folder: Path, settings: Settings
    ):
        """When use_llm=False, the injected judge's write_profile is never called."""
        from photovault.core.learn import learn_from_folder

        fake = FakeJudge()
        settings.llm.enabled = True

        learn_from_folder(
            catalog_folder, "nollm", settings, use_llm=False, judge=fake
        )

        assert len(fake.write_profile_calls) == 0

    def test_judge_not_called_when_llm_disabled_in_settings(
        self, catalog_folder: Path, settings: Settings
    ):
        """When settings.llm.enabled=False, the injected judge is not used."""
        from photovault.core.learn import learn_from_folder

        fake = FakeJudge()
        settings.llm.enabled = False  # disabled via settings

        learn_from_folder(
            catalog_folder, "disabled", settings, use_llm=True, judge=fake
        )

        assert len(fake.write_profile_calls) == 0

    def test_existing_signature_preserved_no_judge(
        self, catalog_folder: Path, settings: Settings
    ):
        """Without judge, the existing behavior (use_llm=False) stays intact."""
        from photovault.core.learn import learn_from_folder
        from photovault.core.profile import load_profile

        report = learn_from_folder(
            catalog_folder, "nojudge", settings, use_llm=False
        )

        assert report.llm_used is False
        prof = load_profile(settings.profiles_dir, "nojudge")
        # Placeholder profile.md is always written.
        assert prof.profile_md is not None


# --------------------------------------------------------------------------- #
# CLI: --no-llm wires through to apply; n_arbitrated surfaced in output
# --------------------------------------------------------------------------- #
class TestCLI:
    """The apply CLI command wires --no-llm and surfaces n_arbitrated."""

    def test_apply_no_llm_flag_suppresses_arbitration(
        self, new_photos: Path, settings: Settings, learned_profile: str, monkeypatch
    ):
        """CLI apply --no-llm: n_arbitrated == 0 in returned report."""
        from unittest.mock import patch

        import typer
        from typer.testing import CliRunner

        from photovault.cli.main import app

        runner = CliRunner()
        # Patch get_settings so the profile dir is the test one.
        with patch("photovault.cli.main.get_settings", return_value=settings):
            result = runner.invoke(
                app,
                ["apply", str(new_photos), "--name", learned_profile, "--no-llm", "--no-report"],
            )
        assert result.exit_code == 0
        # When --no-llm is active: either "arbitrated: 0" or no arbitration line,
        # but the command must succeed without error.

    def test_apply_shows_n_arbitrated_in_output(
        self, new_photos: Path, settings: Settings, learned_profile: str
    ):
        """CLI apply surfaces n_arbitrated in printed summary (value >= 0)."""
        from unittest.mock import patch

        from typer.testing import CliRunner

        from photovault.cli.main import app

        runner = CliRunner()
        with patch("photovault.cli.main.get_settings", return_value=settings):
            result = runner.invoke(
                app,
                ["apply", str(new_photos), "--name", learned_profile, "--no-llm", "--no-report"],
            )
        assert result.exit_code == 0
        # The output should include the arbitrated count.
        assert "arbitrated" in result.output.lower()
