"""Persist and load a Taste Profile on disk.

Layout (see ARCHITECTURE.md §3)::

    <profiles_dir>/<name>/
    ├── meta.json
    ├── presets/*.xmp
    ├── thresholds.json
    ├── labels.csv          # M1 training dataset
    ├── taste_vector.npy    # M2
    ├── classifier.pkl      # M2
    ├── chroma/             # M2
    └── profile.md          # M4 (placeholder written in M1)
"""

from __future__ import annotations

import json
import pickle
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from photovault.core.catalog.style import Preset
from photovault.core.profile.models import ProfileMeta, Thresholds

PROFILE_LAYOUT = {
    "meta": "meta.json",
    "thresholds": "thresholds.json",
    "labels": "labels.csv",
    "presets_dir": "presets",
    "profile_md": "profile.md",
    "taste_vector": "taste_vector.npy",
    "classifier": "classifier.pkl",
    "chroma_dir": "chroma",
}


@dataclass
class LoadedProfile:
    name: str
    path: Path
    meta: ProfileMeta
    thresholds: Thresholds
    preset_files: list[Path]
    profile_md: str | None
    # M2 artifacts; None for M1 profiles that predate them.
    taste_vector: np.ndarray | None = None
    classifier: Any | None = None


def profile_exists(profiles_dir: Path, name: str) -> bool:
    return (profiles_dir.expanduser() / name / PROFILE_LAYOUT["meta"]).exists()


def save_profile(
    profiles_dir: Path,
    name: str,
    meta: ProfileMeta,
    thresholds: Thresholds,
    presets: list[Preset],
    signature: Preset | None = None,
    profile_md: str | None = None,
    labels_csv: Path | None = None,
    taste_vector: np.ndarray | None = None,
    classifier: Any | None = None,
    overwrite: bool = True,
) -> Path:
    """Write the full profile bundle. Returns the profile directory."""
    base = profiles_dir.expanduser() / name
    if base.exists() and overwrite:
        shutil.rmtree(base)
    base.mkdir(parents=True, exist_ok=True)

    (base / PROFILE_LAYOUT["meta"]).write_text(
        meta.model_dump_json(indent=2), encoding="utf-8"
    )
    (base / PROFILE_LAYOUT["thresholds"]).write_text(
        thresholds.model_dump_json(indent=2), encoding="utf-8"
    )

    presets_dir = base / PROFILE_LAYOUT["presets_dir"]
    presets_dir.mkdir(exist_ok=True)
    for preset in presets:
        (presets_dir / f"{preset.name}.xmp").write_text(preset.to_xmp(), encoding="utf-8")
    if signature is not None:
        (presets_dir / "signature.xmp").write_text(signature.to_xmp(), encoding="utf-8")

    if labels_csv is not None and Path(labels_csv).exists():
        shutil.copyfile(labels_csv, base / PROFILE_LAYOUT["labels"])

    md = profile_md or _placeholder_profile_md(name, meta)
    (base / PROFILE_LAYOUT["profile_md"]).write_text(md, encoding="utf-8")

    # M2: L3 pixel artifacts. The chroma/ dir is always created so the vector
    # store has a stable home even when no embeddings were computed.
    if taste_vector is not None:
        np.save(base / PROFILE_LAYOUT["taste_vector"], np.asarray(taste_vector))
    if classifier is not None:
        with (base / PROFILE_LAYOUT["classifier"]).open("wb") as fh:
            pickle.dump(classifier, fh)
    (base / PROFILE_LAYOUT["chroma_dir"]).mkdir(exist_ok=True)

    return base


def load_profile(profiles_dir: Path, name: str) -> LoadedProfile:
    """Load a profile bundle from disk."""
    base = profiles_dir.expanduser() / name
    meta_path = base / PROFILE_LAYOUT["meta"]
    if not meta_path.exists():
        raise FileNotFoundError(f"profile not found: {name} ({base})")

    meta = ProfileMeta.model_validate_json(meta_path.read_text(encoding="utf-8"))
    thresholds = Thresholds.model_validate_json(
        (base / PROFILE_LAYOUT["thresholds"]).read_text(encoding="utf-8")
    )
    presets_dir = base / PROFILE_LAYOUT["presets_dir"]
    preset_files = sorted(presets_dir.glob("*.xmp")) if presets_dir.exists() else []

    md_path = base / PROFILE_LAYOUT["profile_md"]
    profile_md = md_path.read_text(encoding="utf-8") if md_path.exists() else None

    # M2 artifacts are optional (M1 profiles omit them).
    taste_path = base / PROFILE_LAYOUT["taste_vector"]
    taste_vector = np.load(taste_path) if taste_path.exists() else None

    clf_path = base / PROFILE_LAYOUT["classifier"]
    classifier = None
    if clf_path.exists():
        with clf_path.open("rb") as fh:
            classifier = pickle.load(fh)

    return LoadedProfile(
        name=name,
        path=base,
        meta=meta,
        thresholds=thresholds,
        preset_files=preset_files,
        profile_md=profile_md,
        taste_vector=taste_vector,
        classifier=classifier,
    )


def _placeholder_profile_md(name: str, meta: ProfileMeta) -> str:
    """Stub rule-book written until the LLM fills it in at M4."""
    return (
        f"# Taste Profile: {name}\n\n"
        f"*Generated by PhotoVault {meta.version} on "
        f"{meta.created_at.date()}.*\n\n"
        f"- Images analyzed: **{meta.n_images}**\n"
        f"- Keepers: **{meta.n_keepers}**  /  Rejects: **{meta.n_rejects}**\n"
        f"- Representative looks (presets): **{meta.n_presets}**\n\n"
        "> The human-readable taste rule-book is generated by the local Gemma "
        "model in milestone M4 (`photovault learn` will fill this in once the "
        "LLM is enabled). Until then this is a placeholder summary.\n"
    )
